version: '2'
services:
  rails:
    image: rails:5
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    volumes_from:
      - datastore
    ports:
      - '3000:3000'
    command: rails s -b 0.0.0.0
  datastore:
    image: busybox
    volumes:
      - tmp:/usr/src/app/tmp
      - bundle:/usr/local/bundle
volumes:
  bundle:
  tmp:
